import type { UserRole } from '@/types/user'

export const PERMISSION_MATRIX: Record<UserRole, Record<string, boolean>> = {
  cliente: {
    'trips:read': true,
    'trips:write': false,
    'orders:readOwn': true,
    'orders:readAll': false,
    'orders:create': true,
    'payments:readOwn': true,
    'payments:readAll': false,
    'payments:verify': false,
    'payments:reject': false,
    'clients:readOwn': false,
    'clients:readAll': false,
    'commissions:readOwn': false,
    'commissions:readAll': false,
    'analytics:read': false,
    'kpis:read': false,
    'users:read': false,
    'users:manage': false,
    'config:manage': false,
    'notifications:config': true,
    'referrals:create': false,
    'sync:odoo': false,
  },
  agente: {
    'trips:read': true,
    'trips:write': false,
    'orders:readOwn': true,
    'orders:readAll': false,
    'orders:create': true,
    'payments:readOwn': true,
    'payments:readAll': false,
    'payments:verify': false,
    'payments:reject': false,
    'clients:readOwn': true,
    'clients:readAll': false,
    'commissions:readOwn': true,
    'commissions:readAll': false,
    'analytics:read': false,
    'kpis:read': false,
    'users:read': false,
    'users:manage': false,
    'config:manage': false,
    'notifications:config': true,
    'referrals:create': true,
    'sync:odoo': false,
  },
  admin: {
    'trips:read': true,
    'trips:write': true,
    'orders:readOwn': true,
    'orders:readAll': true,
    'orders:create': true,
    'payments:readOwn': true,
    'payments:readAll': true,
    'payments:verify': true,
    'payments:reject': true,
    'clients:readOwn': false,
    'clients:readAll': true,
    'commissions:readOwn': false,
    'commissions:readAll': false,
    'analytics:read': false,
    'kpis:read': false,
    'users:read': true,
    'users:manage': false,
    'config:manage': false,
    'notifications:config': true,
    'referrals:create': false,
    'sync:odoo': true,
  },
  director: {
    'trips:read': true,
    'trips:write': true,
    'orders:readOwn': true,
    'orders:readAll': true,
    'orders:create': false,
    'payments:readOwn': true,
    'payments:readAll': true,
    'payments:verify': false,
    'payments:reject': false,
    'clients:readOwn': false,
    'clients:readAll': true,
    'commissions:readOwn': false,
    'commissions:readAll': true,
    'analytics:read': true,
    'kpis:read': true,
    'users:read': false,
    'users:manage': false,
    'config:manage': false,
    'notifications:config': true,
    'referrals:create': false,
    'sync:odoo': true,
  },
  superadmin: {
    'trips:read': true,
    'trips:write': true,
    'orders:readOwn': true,
    'orders:readAll': true,
    'orders:create': true,
    'payments:readOwn': true,
    'payments:readAll': true,
    'payments:verify': true,
    'payments:reject': true,
    'clients:readOwn': false,
    'clients:readAll': true,
    'commissions:readOwn': false,
    'commissions:readAll': true,
    'analytics:read': true,
    'kpis:read': true,
    'users:read': true,
    'users:manage': true,
    'config:manage': true,
    'notifications:config': true,
    'referrals:create': false,
    'sync:odoo': true,
  },
}

/**
 * Seed permission documents to Firestore /config/permissions/roles/{role}.
 * Idempotent: uses set with merge to avoid overwriting customizations.
 */
export async function runSeed(db: FirebaseFirestore.Firestore): Promise<void> {
  const roles = Object.keys(PERMISSION_MATRIX) as UserRole[]

  for (const role of roles) {
    const ref = db.doc(`config/permissions/roles/${role}`)
    await ref.set(PERMISSION_MATRIX[role], { merge: true })
  }
}
