import type { ContractTemplate } from '@/schemas/contractTemplateSchema'

/**
 * Story 10.1 — Datos del piloto de 5 destinos.
 * Si `contractTemplates` está vacío en Firestore al primer GET, se inicializa con esto.
 * Paloma puede después agregar más destinos creando docs nuevos (Fase 1).
 * Fuente original: plantillas .docx Odoo Documents extraídas en spike-10-1.
 */
export const PILOT_CONTRACT_TEMPLATES: Omit<ContractTemplate, 'templateId'>[] = [
  {
    templateKey: 'vuelta-al-mundo',
    destinoLabel: 'VUELTA AL MUNDO',
    scope: 'internacional',
    plazoLimitePagoDias: 60,
    anexoIncluye: [
      'Boletos de avión saliendo de Ciudad de México y regreso al mismo punto',
      'Alojamiento en hoteles de categoría turista 4 estrellas o similar',
      'Desayunos incluidos provistos por el hotel',
      'Servicio de guía logístico de habla hispana',
      'Traslados a distintos puntos de interés (sujetos a cambios y disponibilidad)',
    ],
    anexoVisitamos: [],
    anexoNoIncluye: [],
    active: true,
    notes: 'Producto bandera AroundaPlanet. Plazo de pago 60 días por complejidad del itinerario internacional.',
  },
  {
    templateKey: 'asia',
    destinoLabel: 'ASIA',
    scope: 'internacional',
    plazoLimitePagoDias: 30,
    anexoIncluye: [
      'Vuelos desde CDMX - ASIA',
      'Vuelos internos',
      'Hospedaje en hoteles 4 estrellas',
      'Traslados aeroportuarios',
      'Desayunos',
      'Guías turísticos de habla hispana',
      'Guías logísticos',
    ],
    anexoVisitamos: ['China', 'Malasia', 'Singapur', 'Tailandia'],
    anexoNoIncluye: [],
    active: true,
    notes: null,
  },
  {
    templateKey: 'europa-septiembre',
    destinoLabel: 'EUROPA SEPTIEMBRE',
    scope: 'internacional',
    plazoLimitePagoDias: 30,
    anexoIncluye: [
      'Vuelos internacionales redondos',
      'Hospedaje 4 estrellas',
      'Desayunos',
      'Traslados aeroportuarios y entre ciudades',
      'Guía logístico de habla hispana',
    ],
    anexoVisitamos: [],
    anexoNoIncluye: [],
    active: true,
    notes: null,
  },
  {
    templateKey: 'colombia-mayo',
    destinoLabel: 'COLOMBIA MAYO',
    scope: 'internacional',
    plazoLimitePagoDias: 30,
    anexoIncluye: [
      'Vuelos redondos desde CDMX',
      'Hospedaje 4 estrellas',
      'Desayunos',
      'Traslados',
      'Guía local de habla hispana',
    ],
    anexoVisitamos: [],
    anexoNoIncluye: [],
    active: true,
    notes: null,
  },
  {
    templateKey: 'chepe-enero',
    destinoLabel: 'CHEPE ENERO',
    scope: 'nacional',
    plazoLimitePagoDias: 30,
    anexoIncluye: [
      'Vuelos redondos (CDMX / Chihuahua - Culiacán / CDMX)',
      'Viaje en el famoso "TREN CHEPE" (Estación Divisadero / El Fuerte Sinaloa)',
      '6 noches en hoteles 4 estrellas',
      'Desayunos',
      'Traslados',
      'Fotografías durante el tour',
      'Coordinadores de grupo',
      'Guías locales',
    ],
    anexoVisitamos: [
      'El Fuerte Sinaloa',
      'Parque Aventura Barrancas del Cobre',
      'Lago Arareko',
      'Cascada Cusárare',
      'Museo Menonita',
      'Ciudad de Chihuahua',
      'Museo Francisco Villa',
      'Museo Nacional Quinta Gameros',
      'Creel (Pueblo Mágico)',
      'Divisadero',
      'Piedra Volada',
      'Valle de las Ranas',
      'Valle de los Hongos',
      'Misión San Ignacio',
      'Barrancas del Cobre',
      'Leyenda del Zorro',
    ],
    anexoNoIncluye: [
      'Alimentos y bebidas no incluidos',
      'Actividades en Parque Aventura',
    ],
    active: true,
    notes: null,
  },
]
